### ISSUE TITLE
INFOGRAFIA_GENARO SANTIAGO VALENTÍN

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Valentiin01#2]
[GENARO SANTIAGO VALENTÍN.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Valentiin01/files/12541536/GENARO.SANTIAGO.VALENTIN.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
